version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER = postgres'
      - 'POSTGRES_PASSWORD = 123'
      - 'POSTGRES_DB = pricing'

  app:
    build: ./
    container_name: 'pricing-app'
    ports:
      - "80:80"